name = "Transparency"
uuid = "be247f3c-b89e-4149-9092-0bc3d48f38b6"
authors = ["Tiago M. D. Pereira"]
version = "0.1.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Interpolations = "0.12, 0.13"
NumericalIntegration = "^0.3"
PhysicalConstants = "^0.2"
SpecialFunctions = "^1.2.1"
Unitful = "1"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
